version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_SOCKET_LISTEN_PORT=8000
      - FLASK_SOCKET_LISTEN_HOST=0.0.0.0
      - POLICY_SERVER_PORT=5002
      - POLICY_SERVER_HOST=0.0.0.0
      - CORS_DOMAIN=http://localhost
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./postfixer-frontend
      args:
        - REACT_APP_API_BASE_URL=/api
        - REACT_APP_SOCKET_URL=/
    ports:
      - "80:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: